<?php

/**
 * @file
 * Implementing our hooks.
 */

/**
 * Implements hook_theme().
 */
function module_hero_theme($existing, $type, $theme, $path) {

  return [
    'hero_list' => [
      'variables' => ['items' => [], 'title' => ''],
    ]
  ];
}

function module_hero_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if($form_id == "node_article_form"){
    $form['field_tags']['#access'] = FALSE;
    $form['title']['widget']['0']['value']['#title'] = t('Article Title');
    //kint($form); die();

    $form['#validate'][] = '_module_hero_article_validate';
  }
  
}

function _module_hero_article_validate(&$form, $form_state){
//kint($form_state->getValue('title')[0]['value']); die(); 
if(is_numeric($form_state->getValue('title')[0]['value'])){
  $form_state->setErrorByName('title', t('Title should not be a number!'));
}
}